version: '3'

services:
  portfolio:
    build:
      context: /home/romain-poisson/docker/react-portfolio
      dockerfile: /home/romain-poisson/docker/react-portfolio/Dockerfile
    container_name: portfolio-app
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=portfolio.romainpoisson.com
      - LETSENCRYPT_HOST=portfolio.romainpoisson.com
      - LETSENCRYPT_EMAIL=admin@romainpoisson.com
    networks:
      - nginx-proxy
      - default

networks:
  nginx-proxy:
    external: true