version: '3'

services:
  portfolio:
    build:
      context: https://github.com/webromain/react-portfolio.git#main
      dockerfile: Dockerfile
    container_name: portfolio-app
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=portfolio.romainpoisson.com
      - LETSENCRYPT_HOST=portfolio.romainpoisson.com
      - LETSENCRYPT_EMAIL=admin@romainpoisson.com
    networks:
      - nginx-proxy
      - default

networks:
  nginx-proxy:
    external: true