version: '3'

services:
  portfolio:
    build:
      context: https://github.com/webromain/react-portfolio.git#main
      dockerfile: Dockerfile
    container_name: portfolio-app
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=portfolio.romainpoisson.com
      - LETSENCRYPT_HOST=portfolio.romainpoisson.com
      - LETSENCRYPT_EMAIL=admin@romainpoisson.com
    networks:
      - nginx-proxy
      - default
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 portfolio-app
    restart: always

networks:
  nginx-proxy:
    external: true